### PR TITLE
fixed get_school_name to sucessfully retrieve school name and get_name function from School.py

### PR DESCRIPTION
**Pull request by ChrisBryann**

### CODE REVIEW

**Comment by Nobelz** [comment]
Can you accept the PR on your branch and update this PR? I need to check if it passes my workflows and the workflows were broken due to the fact that the new version changed how they worked.

**Review by Nobelz — CHANGES_REQUESTED** [review]
Add line in workflows to fix (See PR [#1](https://github.com/ChrisBryann/RateMyProfessorAPI/pull/1))

**Comment by ChrisBryann** [comment]
@Nobelz just approved the PR.

**Review by Nobelz — APPROVED** [review]
Approved with revisions.
Revisions:
- Updated incorrect test
- Removed f string to be compatible with Python 3.5

**Pull request merged**
