### PR TITLE
Added deep find for professor

### PR DESCRIPTION
**Pull request by Ozeitis**
Added deep_get_professor_by_school_and_name(college: School, professor_name: str):

It is the same as get_professor_by_school_and_name, but splits the name, creating a list of possible names. Then it searches for the professor with the highest similarity rating when compared to the passed professor name.

### CODE REVIEW

**Comment by Ozeitis** [comment]
Finally got around to doing it, may need some cleaning up and I don't know how to write tests so I wrote my tests in examples.py instead.

**Comment by Nobelz** [comment]
Great, but is there any reason why it's failing the checks?

**Comment by Nobelz** [comment]
Also, can you add the new imports to requirements.txt?

**Review by Nobelz — CHANGES_REQUESTED** [review]
Please merge new changes on master branch in order for me to run checks.

**Comment by Nobelz** [comment]
Closing due to inactivity. If anyone wants to pick up #3 please do.

**Pull request closed without merging**
