### PR TITLE
Update comment field of Professor

### PR DESCRIPTION
**Pull request by Ozeitis**
Currently, comments from the rating class return comments with horribly formatted HTML special characters, these changes will fix that.

### CODE REVIEW

**Review by Nobelz — CHANGES_REQUESTED** [review]
@Ozeitis Automated checks on your PR have failed largely due to my failure to maintain this repo over the past year; as a result, I'm not able to review your comments until you accept my pull request on your patch-1 branch with updated fixes. Sorry for the inconvenience.

**Comment by Ozeitis** [comment]
Apologies, I was traveling. I have done what you have asked. I hope to try to add more meaningful edits to this as a major project I am making is highly reliant on this. Very much appreciate all this work! I am a 1st year Comp Sci student so trying to get some projects under my belt :)

**Comment by Nobelz** [comment]
> Apologies, I was traveling. I have done what you have asked. I hope to try to add more meaningful edits to this as a major project I am making is highly reliant on this. Very much appreciate all this work! I am a 1st year Comp Sci student so trying to get some projects under my belt :)

No worries, I am a 2nd year Comp Sci student so I am very new to this as well, as you may be able to tell :) I'm honored that you've chosen to use this API and hopefully it will get better over time as more experienced people teach me the methods to maintain this repo. 

As for your latest changes, thank you for merging the pull request, however it still fails to pass the checks because of some issue with lxml, I'm going to try importing lxml and see if that solves the problem.

**Comment by Nobelz** [comment]
I have merged your pull request for the time being, as it now passes all preliminary checks. Before releasing v1.3.0, however, I will perform additional checks to ensure that it works as intended.
Thanks.
-Nobel

**Comment by Nobelz** [comment]
Your changes are now reflected in Release v1.3.0. Thanks for your contributions!

**Pull request merged**
